Script1_Linear_Regression_Normalised_by_Covariates.R foldchange_exercise.csv metadata.csv
Script2_Paired_Wilcoxon_Test.R exercise_before.csv exercise_after.csv
Script3_Random_Forest_Model.R exercise_baseline.csv grouping.csv
